apiVersion: v1
kind: Route
metadata:
  name: {{ include "webapp-chart.fullname" . }}
  labels:
    {{- include "webapp-chart.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "webapp-chart.fullname" . }}
    weight: 100
  port:
    targetPort: {{ .Values.service.targetPort }}
  wildcardPolicy: None
